name: Sync master

on:
  schedule:
  - cron: "20 4 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "noreply@github.com"

      - name: Add upstream & fetch
        run: |
          git remote add upstream https://github.com/qemu/qemu.git
          git fetch upstream

      - name: Reset master to upstream/master
        run: git reset --hard upstream/master

      - name: Push
        run: git push --force-with-lease origin master
